name: bloc_architecture
description: A Flutter project for learning Bloc architecture.
version: 1.1.0
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  auto_route: ^10.1.0+1
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  ui:
    path: packages/ui

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  build_runner: ^2.5.1
  flutter_test:
    sdk: flutter
  melos: ^6.3.3
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
